print('''\033[1;36;40m
*****************************************************

     .... NO! ...                  ... MNO! ...
   ..... MNO!! ...................... MNNOO! ...
 ..... MMNO! ......................... MNNOO!! .
..... MNOONNOO!   MMMMMMMMMMPPPOII!   MNNO!!!! .
 ... !O! NNO! MMMMMMMMMMMMMPPPOOOII!! NO! ....
    ...... ! MMMMMMMMMMMMMPPPPOOOOIII! ! ...
   ........ MMMMMMMMMMMMPPPPPOOOOOOII!! .....
   ........ MMMMMOOOOOOPPPPPPPPOOOOMII! ...
    ....... MMMMM..    OPPMMP    .,OMI! ....
     ...... MMMM::   o.,OPMP,.o   ::I!! ...
         .... NNM:::.,,OOPM!P,.::::!! ....
          .. MMNNNNNOOOOPMO!!IIPPO!!O! .....
         ... MMMMMNNNNOO:!!:!!IPPPPOO! ....
           .. MMMMMNNOOMMNNIIIPPPOO!! ......
          ...... MMMONNMMNNNIIIOO!..........
       ....... MN MOMMMNNNIIIIIO! OO ..........
    ......... MNO! IiiiiiiiiiiiI OOOO ...........
  ...... NNN.MNO! . O!!!!!!!!!O . OONO NO! ........
   .... MNNNNNO! ...OOOOOOOOOOO .  MMNNON!........
   ...... MNNNNO! .. PPPPPPPPP .. MMNON!........
      ...... OO! ................. ON! .......
         ................................

*****************************************************
''')

print("\033[1;37;40mWelcome to Treasure Island!\n")
print("\033[1;37;40mYe has come to find me treasure me thinks. Let's see if ye can find it. \n")
print("\033[1;37;40mBeware! There be danger on this here island!\n")

step_1 = input(
    "\033[1;35;40mYou have come to the end of the beach and see two paths. You can only go left or right. Where do you want to go? Type 'left' or 'right': \033[1;36;40m")

if step_1 == ("left") or step_1 == ("Left"):

    step_2 = input(
        "\033[1;35;40m\nYou have come to a river. You need to get to the other side. Type 'wait' to wait for a boat or type 'swim' to swim across: \033[1;36;40m")
    if step_2 == ("wait") or step_2 == ("Wait"):

        step_3 = input(
            "\033[1;35;40m\nYou arrive at the other side unharmed. There is a house with three doors. One red, one yellow and one blue. Which colour do you want to go through? Type\033[1;31;40m red\033[1;35;40m,\033[1;33;40m yellow\033[1;35;40m or\033[1;34;40m blue\033[1;35;40m. \033[1;36;40m")
        if step_3 == ("red") or step_3 == ("Red"):
            print("\033[1;31;40m\nYe enter a room full of fire. Game Over.")
        elif step_3 == ("blue") or step_3 == ("Blue"):
            print("\033[1;34;40m\nYe enter a room of beasts. Game Over.")
        elif step_3 == ("yellow") or step_3 == ("Yellow"):
            print("\033[1;33;40m\nYe found me treasure! You Win!\n")
        else:
            print(
                "\n\033[1;31;40mYou chose a door that doesn't exist. Game Over.")

    else:
        print(
            "\n\033[1;31;40mYou get attacked by an angry crocodile. Game Over.")

else:
    print("\033[1;31;40m\nYou fell into a pit of snakes. Game Over.")
